packages:
  - 'backend'
  - 'web'

allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false

onlyBuiltDependencies:
  - esbuild
  - workerd
  - sharp
  - '@esbuild/win32-x64'
  - '@img/sharp-win32-x64'